module.exports = {
  content: ['dist/**/*.html', 'dist/_astro/*.js'],
  css: ['public/assets/css/theme.bundle.css'],
  output: '/tmp/theme.purged.css',
  safelist: {
    standard: [
      'aos-init',
      'aos-animate',
      'show',
      'collapsing',
      'fade',
      'collapsed',
      'active',
      'disabled',
    ],
    deep: [
      /:root/,
      /data-bs-theme/,
      /^a($|:)/,
      /^address/,
      /^b/,
      /^body/,
      /^button/,
      /^caption/,
      /^code/,
      /^dd/,
      /^dl/,
      /^dt/,
      /^fieldset/,
      /^figure/,
      /^h[1-6]/,
      /^hr/,
      /^html/,
      /^iframe/,
      /^img/,
      /^input/,
      /^kbd/,
      /^label/,
      /^legend/,
      /^mark/,
      /^ol/,
      /^optgroup/,
      /^output/,
      /^p($|[,:>+~ ])/,
      /^samp/,
      /^select/,
      /^small/,
      /^strong/,
      /^sub/,
      /^summary/,
      /^sup/,
      /^svg/,
      /^table/,
      /^tbody/,
      /^td/,
      /^textarea/,
      /^tfoot/,
      /^th/,
      /^thead/,
      /^tr/,
      /^ul/,
      /^\*/,
      /^::/,
      /^:before/,
      /^:after/,
    ],
  },
};
